---
title: "Mental_Health_H2O_models"
author: "Niket Choudhary"
date: "July 28, 2018"
output: rmarkdown::github_document
---

```{r}
mhealth_2 <- read.csv(file.choose(), header = TRUE, na.strings = c("NA", "", " ", "."))
```


```{r}
set.seed(1234)
oneortwo <- sample(1:2 , length(mhealth_2$Age), replace = TRUE, prob=c(0.8, 0.2)) # generating random values and storing them
```

```{r}
# create train data frame
train <- mhealth_2[oneortwo == 1, ]

# create test data frame
test <- mhealth_2[oneortwo == 2, ]
```


```{r}
# install.packages("data.table")
library(data.table)
```


```{r}
# install.packages("h2o")
```

```{r}
library(h2o)
```

```{r}
localH2O <- h2o.init(nthreads = -1)
```


Let’s now transfer the data from R to h2o instance
```{r}
# data to h2o cluster
train.h2o <- as.h2o(train)
test.h2o <- as.h2o(test)
```

```{r}
colnames(train.h2o)
```

```{r}
#dependent variable (work_interfere)
y.dep <- 7
```

```{r}
#independent variables 
x.indep <- c(1:6, 8:24)
```


```{r}
#install.packages('caret')
require(caret)

#install.packages('e1071')
require(e1071)

#install.packages('randomForest')
library(randomForest)
```

### Random Forest
```{r}
system.time(
rforest.model <- h2o.randomForest(y = y.dep, x = x.indep, training_frame = train.h2o, ntrees = 100, mtries = 12, max_depth = 4, seed = 1234)
)
```

```{r}
h2o.performance(rforest.model)
```

```{r}
# making predictions on unseen data
system.time(predict.rforest <- as.data.frame(h2o.predict(rforest.model, test.h2o)))
```


```{r}
results <- as.data.table(predict.rforest)
results_1 <- union(results$predict, test$work_interfere)
confusionMatrix(table(factor(results$predict, results_1), factor(test$work_interfere, results_1)))
```

***

### GBM
```{r}

system.time(
gbm.model <- h2o.gbm(y = y.dep, x = x.indep, training_frame = train.h2o, ntrees = 100, max_depth = 4, learn_rate = 0.01, seed = 1234)
)
```

```{r}
h2o.performance (gbm.model)
```


```{r}
predict.gbm <- as.data.frame(h2o.predict(gbm.model, test.h2o))
```

```{r}
results2 <- as.data.table(predict.gbm)
results_2 <- union(results2$predict, test$work_interfere)
confusionMatrix(table(factor(results2$predict, results_2), factor(test$work_interfere, results_2)))
```

***

### Deep learning models
```{r}
system.time(
             dlearning.model <- h2o.deeplearning(y = y.dep,
             x = x.indep,
             training_frame = train.h2o,
             epoch = 15,
             hidden = c(100, 100),
             activation = "Rectifier",
             seed = 1234
             )
)
```

```{r}
h2o.performance(dlearning.model)
```

```{r}
predict.dl2 <- as.data.frame(h2o.predict(dlearning.model, test.h2o))
```

```{r}
results3 <- as.data.table(predict.dl2)
results_3 <- union(results3$predict, test$work_interfere)
confusionMatrix(table(factor(results3$predict, results_3), factor(test$work_interfere, results_3)))
```

***

Across all three models our accuracy has was highest inRandom Forest.
